spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

jwt:
  secret: "${JWT_SECRET}"
  access-token:
    expiration: 3600000

server:
  port: 19095